/*

 ALFI.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 16

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define alfiBank 0

/* Super Gameboy palette 0 */
#define alfiSGBPal0c0 6076
#define alfiSGBPal0c1 8935
#define alfiSGBPal0c2 6596
#define alfiSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define alfiSGBPal1c0 6076
#define alfiSGBPal1c1 8935
#define alfiSGBPal1c2 6596
#define alfiSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define alfiSGBPal2c0 6076
#define alfiSGBPal2c1 8935
#define alfiSGBPal2c2 6596
#define alfiSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define alfiSGBPal3c0 6076
#define alfiSGBPal3c1 8935
#define alfiSGBPal3c2 6596
#define alfiSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define alfiCGBPal0c0 31710
#define alfiCGBPal0c1 28209
#define alfiCGBPal0c2 0
#define alfiCGBPal0c3 32767

/* Gameboy Color palette 1 */
#define alfiCGBPal1c0 6076
#define alfiCGBPal1c1 8935
#define alfiCGBPal1c2 6596
#define alfiCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define alfiCGBPal2c0 6076
#define alfiCGBPal2c1 8935
#define alfiCGBPal2c2 6596
#define alfiCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define alfiCGBPal3c0 6076
#define alfiCGBPal3c1 8935
#define alfiCGBPal3c2 6596
#define alfiCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define alfiCGBPal4c0 6076
#define alfiCGBPal4c1 8935
#define alfiCGBPal4c2 6596
#define alfiCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define alfiCGBPal5c0 6076
#define alfiCGBPal5c1 8935
#define alfiCGBPal5c2 6596
#define alfiCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define alfiCGBPal6c0 6076
#define alfiCGBPal6c1 8935
#define alfiCGBPal6c2 6596
#define alfiCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define alfiCGBPal7c0 6076
#define alfiCGBPal7c1 8935
#define alfiCGBPal7c2 6596
#define alfiCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char alfiCGB[];
/* Start of tile array. */
extern unsigned char alfi[];

/* End of ALFI.H */
