/*

 LOGO_SET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 118

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define logo_setBank 0

/* Super Gameboy palette 0 */
#define logo_setSGBPal0c0 6076
#define logo_setSGBPal0c1 8935
#define logo_setSGBPal0c2 6596
#define logo_setSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define logo_setSGBPal1c0 6076
#define logo_setSGBPal1c1 8935
#define logo_setSGBPal1c2 6596
#define logo_setSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define logo_setSGBPal2c0 6076
#define logo_setSGBPal2c1 8935
#define logo_setSGBPal2c2 6596
#define logo_setSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define logo_setSGBPal3c0 6076
#define logo_setSGBPal3c1 8935
#define logo_setSGBPal3c2 6596
#define logo_setSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define logo_setCGBPal0c0 32767
#define logo_setCGBPal0c1 8935
#define logo_setCGBPal0c2 6596
#define logo_setCGBPal0c3 0

/* Gameboy Color palette 1 */
#define logo_setCGBPal1c0 6076
#define logo_setCGBPal1c1 8935
#define logo_setCGBPal1c2 6596
#define logo_setCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define logo_setCGBPal2c0 6076
#define logo_setCGBPal2c1 8935
#define logo_setCGBPal2c2 6596
#define logo_setCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define logo_setCGBPal3c0 6076
#define logo_setCGBPal3c1 8935
#define logo_setCGBPal3c2 6596
#define logo_setCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define logo_setCGBPal4c0 6076
#define logo_setCGBPal4c1 8935
#define logo_setCGBPal4c2 6596
#define logo_setCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define logo_setCGBPal5c0 6076
#define logo_setCGBPal5c1 8935
#define logo_setCGBPal5c2 6596
#define logo_setCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define logo_setCGBPal6c0 6076
#define logo_setCGBPal6c1 8935
#define logo_setCGBPal6c2 6596
#define logo_setCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define logo_setCGBPal7c0 6076
#define logo_setCGBPal7c1 8935
#define logo_setCGBPal7c2 6596
#define logo_setCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char logo_setCGB[];
/* Start of tile array. */
extern unsigned char logo_set[];

/* End of LOGO_SET.H */
